name: Build and Push Docker Image

on:
  push:
    branches:
      - release

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: moonbse/blog:latest

  deploy:
    name: Deploy
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Generate X-Hub-Signature
        id: generate-signature
        shell: bash
        run: |
          payload='{"app-id" : "blog"}'
          secret="${{secrets.WEBHOOK_SECRET}}"
          signature=$(echo -n "$payload" | openssl dgst -sha256 -hmac "$secret" | awk '{print $2}')
          echo "signature=sha256=$signature" >> $GITHUB_ENV

      -  name: Deploy Stage
         uses: fjogeleit/http-request-action@v1
         with:
          url: 'https://nirbhaysingh.org/hooks/webhook'
          method: 'POST'
                
          customHeaders: '{"Content-Type": "application/json", "X-Hub_Signature" : "${{env.signature}}"}'
          data: '{"app-id": "test"}'          